# Generated by Django 6.0.1 on 2026-01-11 08:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email адрес")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("middle_name", models.CharField(blank=True, max_length=150, null=True, verbose_name="Отчество")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="RU", verbose_name="Телефон"
                    ),
                ),
                ("telegram_id", models.CharField(blank=True, max_length=100, null=True, verbose_name="Telegram ID")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/", verbose_name="Фотография"),
                ),
                ("organization", models.CharField(blank=True, max_length=255, null=True, verbose_name="Организация")),
                ("department", models.CharField(blank=True, max_length=255, null=True, verbose_name="Отдел")),
                ("position", models.CharField(blank=True, max_length=255, null=True, verbose_name="Должность")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Персонал")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "indexes": [
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["last_name", "first_name"], name="users_user_last_na_be362d_idx"),
                    models.Index(fields=["is_active"], name="users_user_is_acti_ddda02_idx"),
                    models.Index(fields=["department"], name="users_user_departm_52fe15_idx"),
                    models.Index(fields=["position"], name="users_user_positio_80eb68_idx"),
                ],
            },
        ),
    ]
