# Generated by Django 6.0.1 on 2026-01-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["is_active", "employee"], name="organizatio_is_acti_b09b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["level", "is_active"], name="organizatio_level_6fc2d8_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["department", "is_active"], name="organizatio_departm_a85bb9_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["is_active"], name="organizatio_is_acti_7598da_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["employee"], name="organizatio_employe_6c9403_idx"),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("name", "department"), name="unique_position_name_in_department"
            ),
        ),
    ]
